-- MySQL Script generated by MySQL Workbench
-- Tue Jun 16 18:24:27 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema borrow_money
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema borrow_money
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `borrow_money` DEFAULT CHARACTER SET utf8 ;
USE `borrow_money` ;

-- -----------------------------------------------------
-- Table `borrow_money`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `borrow_money`.`customer` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `occupation` VARCHAR(45) NULL,
  `monthlyIncome` DECIMAL(12,2) NULL,
  `citizenNumber` VARCHAR(13) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `borrow_money`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `borrow_money`.`Admin` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `bankName` VARCHAR(50) NULL,
  `bankAccount` VARCHAR(20) NULL,
  `bankAccountName` VARCHAR(100) NULL,
  `promptpayId` VARCHAR(13) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `borrow_money`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `borrow_money`.`loan` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `amount` DECIMAL(12,2) NULL,
  `rate` DECIMAL(5,2) NULL,
  `month` INT NULL,
  `dueDate` DATETIME NULL,
  `purpose` VARCHAR(255) NULL,
  `loanStatus` VARCHAR(10) NULL,
  `cdnurl` VARCHAR(500) NULL,
  `customer_id` INT NOT NULL,
  `Admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_loan_customer1_idx` (`customer_id` ASC),
  INDEX `fk_loan_Admin1_idx` (`Admin_id` ASC),
  CONSTRAINT `fk_loan_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `borrow_money`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_loan_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `borrow_money`.`Admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `borrow_money`.`guarantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `borrow_money`.`guarantor` (
  `id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  `name` VARCHAR(80) NULL,
  `phone` VARCHAR(10) NULL,
  `citizenNumber` VARCHAR(13) NULL,
  `relationship` VARCHAR(30) NULL,
  `loan_id1` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_guarantor_loan1_idx` (`loan_id1` ASC),
  CONSTRAINT `fk_guarantor_loan1`
    FOREIGN KEY (`loan_id1`)
    REFERENCES `borrow_money`.`loan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `borrow_money`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `borrow_money`.`payment` (
  `id` INT NOT NULL,
  `loan_id` INT NOT NULL,
  `payDate` DATETIME NULL,
  `payAmount` DECIMAL(12,2) NULL,
  `lateFee` DECIMAL(10,2) NULL,
  `method` VARCHAR(15) NULL,
  `cdnurl` VARCHAR(500) NULL,
  `stats` ENUM("รอตรวจ", "อนุมัติ", "ปฏิเสธ") NULL DEFAULT 'รอตรวจ',
  `Admin_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_Admin1_idx` (`Admin_id` ASC),
  INDEX `fk_payment_loan_idx` (`loan_id` ASC),
  CONSTRAINT `fk_payment_Admin1`
    FOREIGN KEY (`Admin_id`)
    REFERENCES `borrow_money`.`Admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_loan`
    FOREIGN KEY (`loan_id`)
    REFERENCES `borrow_money`.`loan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
